FROM nginx:1.11

MAINTAINER azure <baiyue.one>

ENV TZ=Asia/Shanghai

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY ./site /usr/share/nginx/html

RUN chmod a+w /usr/share/nginx/html/conf/application.ini && \
    chmod -R a+w+r /usr/share/nginx/html/install/ && \
    chmod -R a+w+r /usr/share/nginx/html/temp && \
    chmod -R a+w /usr/share/nginx/html/log
